//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioSOAP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int PersonaId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string NIF { get; set; }
        public string Direccion { get; set; }
        public string EstadoCivil { get; set; }
        public string Sexo { get; set; }
        public string CodigoPostal { get; set; }
        public string Provincia { get; set; }
    }
}
